Repository 404-SpongeBob-SquarePants/CMPUT404-project-socialdistribution, pull requests merged in 2020-03, with the labels that each got.

#22 update friend status done
  mysite/friend/serializers.py
  mysite/friend/views.py
Labels: Back-end

#25 fix friend bugs
  mysite/comment/migrations/0001_initial.py
  mysite/friend/migrations/0001_initial.py
  mysite/friend/migrations/0002_auto_20200228_2328.py
  mysite/friend/migrations/0002_auto_20200306_2052.py
  mysite/friend/models.py
  mysite/friend/permissions.py
  mysite/friend/serializers.py
  mysite/friend/views.py
  mysite/node/migrations/0001_initial.py
  mysite/node/views.py
  mysite/post/migrations/0001_initial.py
  mysite/user/migrations/0001_initial.py
  mysite/user/models.py
  mysite/user/validators.py
  mysite/user/views.py
Labels: Back-end, bug, enhancement

#32 update friend permission
  mysite/friend/permissions.py
  mysite/friend/serializers.py
  mysite/friend/urls.py
  mysite/friend/views.py
Labels: Back-end, bug, enhancement

#41 changed the timezone to MST7MDT
  mysite/mysite/settings.py
Labels: Back-end, bug

#48 code clean and add new features
  myblog/src/Login.js
  myblog/src/Routes.js
  myblog/src/Settings.js
  myblog/src/User.js
  myblog/src/UserSelf.js
  myblog/src/components/AuthorHeader.js
  myblog/src/components/AuthorProfile.js
  myblog/src/index.js
Labels: Front-end, enhancement

#49 fixed bug in viewing an authot's posts as another author
  mysite/user/views.py
Labels: Back-end, bug

#53 code clean
  myblog/src/FriendRequest.js
  myblog/src/FriendsList.js
  myblog/src/Login.js
  mysite/comment/migrations/0001_initial.py
  mysite/friend/migrations/0001_initial.py
  mysite/node/migrations/0001_initial.py
  mysite/post/migrations/0001_initial.py
  mysite/user/migrations/0001_initial.py
  mysite/user/models.py
  mysite/user/serializers.py
Labels: Front-end

#64 Be test post api
  mysite/post/tests.py
  mysite/post/views.py
  mysite/user/views.py
Labels: Back-end, bug

#69 code clean and bug fix
  myblog/src/FriendRequest.js
  myblog/src/FriendsList.js
  myblog/src/Login.js
  myblog/src/PostEdit.js
  myblog/src/PostInput.js
  myblog/src/Settings.js
  myblog/src/User.js
  myblog/src/UserSelf.js
  myblog/src/components/AuthorHeader.js
  myblog/src/components/AuthorProfile.js
  myblog/src/utils/constants.js
  myblog/src/utils/utils.js
Labels: Front-end, bug

#79 add friend api test
  friend/tests.py
Labels: Back-end

#125 Update friend page api
  src/FriendRequest.js
  src/FriendsList.js
Labels: Front-end

#124 combine local visible posts and remote posts
  post/views.py
Labels: Back-end

#138 fix cannot get remote author bug
  post/views.py
  src/SearchPage.js
  user/views.py
Labels: Back-end

#139 changed comment to drawer format
  post/views.py
  src/404.css
  src/404.js
  src/Comment.js
  src/Register.js
  src/User.js
  src/UserSelf.js
  src/components/AuthorHeader.js
Labels: Front-end

#140 Fe feature comment
  src/Comment.js
  src/User.js
  src/UserSelf.js
Labels: Front-end

#142 bug fixed
  src/components/AuthorProfile.js
Labels: Front-end

#146 changed postInput css
  package-lock.json
  src/PostEdit.js
  src/PostInput.js
  src/components/PostInput.css
Labels: Front-end

#145 add user test case
  user/tests.py
Labels: Back-end

#143 fix friend and friend request bug
  src/FriendRequest.js
  src/FriendsList.js
Labels: Front-end

#148 add success message when send friend request
  src/UserSelf.js
  src/components/AuthorProfile.js
Labels: Front-end

#149 Be remote comments
  comment/models.py
  comment/views.py
  friend/views.py
  node/models.py
  post/models.py
  post/views.py
  user/views.py
Labels: Back-end, enhancement

#153 comment code clean
  src/Comment.js
Labels: Front-end

#154 Fe comment bug
  src/Comment.js
  src/User.js
  src/UserSelf.js
Labels: Front-end, bug

#156 add loading to friend and friend request
  src/FriendRequest.js
  src/FriendsList.js
Labels: Front-end, enhancement

#167 optimized the UI
  src/Comment.js
  src/FriendRequest.js
  src/FriendsList.js
  src/PostInput.js
  src/User.js
  src/UserSelf.js
Labels: Front-end, enhancement
